build:
  image: library/node:6.9.1
  commands:
    - npm install yarn -g
    - yarn install --ignore-engines
    - yarn run lint
    - yarn test

notify:
  slack:
    webhook_url: $$SLACK_RELEASES_WEBHOOK
    channel: releases
    username: drone

publish:
  npm:
    username: "$$NPM_USERNAME"
    password: "$$NPM_PASSWORD"
    email: "$$NPM_EMAIL"
    when:
      event: tag
